### ISSUE TITLE
Plugin does not respect settings from DOI PubId Plugin

### ISSUE THREAD

**Issue by ctgraham** [VTUL/EzidDOI#3] opened 2015-09-22 15:11 UTC
DOI formatting specified in the DOI PubId Plugin configuration is lost when registering articles with the EzioDOI plugin.

Steps to reproduce:
- Configure DOI Plugin Settings (for example)
  - Articles (x)
  - Prefix: "10.5072"
  - DOI Suffix: "FK2%j.%Y.%a" for articles
- Confirm custom DOI assignment by visiting article
- Confirm custom DOI assignment by exporting article via EZID Export/Registration
  -  EZID Export/Registration Plugin ->
  - (Export) Unregistered Articles ->
  - (Select Article) Export
- (Select Article) Register

Expected result: Article is registered with DOI as previewed.
Actual result: A new DOI is generated and registered.

**Comment by ctgraham** [comment] 2015-09-22 15:17
~~Maybe this is a function of the test DOI handle?  The correct DOI is being sent to EZID.~~
It looks like I already had some DOIs with a different prefix inadvertently assigned.  When submitting this existing DOI against the test prefix, a new DOI was generated and overwritten locally.  Still a bit confused, but getting closer.

**Comment by logpanic** [comment] 2015-09-22 16:29
So was the DOI that was generated and overwritten compliant with the PubID settings (per your expected result example) or a completely new DOI (per your actual result example)?

**Comment by ctgraham** [comment] 2015-09-22 18:19
My DOI Plugin was configured as: 10.5072/FK2%j.%Y.%a .
The EZID Plugin was configured with a shoulder of 10.5072/FK2
The existing DOI was 10.5195/lesli.2013.3
When submitted to EZID, the returned DOI was doi:10.5072/FK2ZP41D8Q

~~It seems like an odd combination of user error and unexpected results from the EZID webservice.  With a bit more research to confirm this, I think I'll be able to adjust this issue title and offer a PR.~~

I also just replicated this with what I thought would have been a "correct" setup:
My DOI Plugin: 10.5072/FK2%j.%Y.%a .
The EZID Plugin shoulder: 10.5072/FK2
The existing DOI: 10.5072/FK2lesli.2013.6637
EZID returned DOI: doi:10.5072/FK2P84891G

So I'm confused again.  I will bounce this off of EZID support.

**Comment by ctgraham** [comment] 2015-09-22 18:45
Ok, I think I've found the answer.  This plugin only supports [minting DOIs by shoulder](http://ezid.cdlib.org/doc/apidoc.html#operation-mint-identifier) currently, correct?  My pull request will be to add [creating DOIs as well](http://ezid.cdlib.org/doc/apidoc.html#operation-create-identifier).

**Comment by ctgraham** [comment] 2015-09-23 20:27
Enabling this functionality will depend on https://github.com/pkp/pkp-lib/pull/769 and maybe a little bit of coordination with the DOI PubId Plugin.  Perhaps the DOI should specify the shoulder, rather than this plugin?  Or maybe the presence of the shoulder in this plugin should enforce minting, and the absence of the shoulder defer to creation per the DOI PubId Plugin?

**Comment by logpanic** [comment] 2015-09-23 20:37
I'm apt to go with the second route, where the default is whatever is specified in the PubId plugin which would result in creation and this plugin would provide an override and result in minting.

**Comment by ctgraham** [comment] 2015-09-24 13:46
I can run with the plan for using the shoulder to enforce minting rather than using the PubId plugin settings.  @chasehd, are you familiar with the plugin's "testMode"? It is tied into the shoulder setting, a bit awkwardly (or so it seems from my reading).

It seems to entirely hinge on taking the existing DOI, replacing everything before the first slash with the plugin's shoulder, and using that as the registered DOI.
https://github.com/VTUL/EzidDOI/blob/378fed0199883a5596e3c27282e4d68f3865e5fe/EzidRegisterPlugin.inc.php#L426-L428

If the $testPrefix parameter for this method is actually the test prefix, this seems sensible.  If the $testPrefix is another passed in shoulder, however, this would leave nonsensical data.

I suspect "testMode" is a workaround for this issue (losing the originally stored DOI) and that the testMode can be removed in my PR, but I'm not confident that I have the original use-case figured out.

**Comment by logpanic** [comment] 2015-09-24 15:26
From what I can tell, it looks like testMode was brought over from the DOIExportPlugin and tests for...testMode. I'm not sure how to enable testMode, however. markRegistered does the `regex_replace` only if it's in testMode. Otherwise, it just grabs the doi that was already set (using the shoulder) right before the call to markRegistered:
https://github.com/VTUL/EzidDOI/blob/378fed0199883a5596e3c27282e4d68f3865e5fe/EzidRegisterPlugin.inc.php#L357-L365

**Comment by ctgraham** [comment] 2015-09-24 17:48
I concur.  It looks like testMode was brought over from the datacite or crossref source and doesn't really apply to this plugin.  It can be enabled only by manually appending the testMode parameter to the URI.

**Comment by logpanic** [comment] 2015-10-02 21:27
Okay, I think I may have this worked out. And it does depend on pkp/pkp-lib#769 getting pushed up stream. I copied over the dev version your commit was merged into and it works with this commit https://github.com/chasehd/EzidDOI/commit/90a6d58eb9503896bbb18a7521fdbc2fcb0ce702

**Comment by logpanic** [comment] 2015-10-20 16:21
Everything seems to work as intended; however, a doi_data node isn't added to the issue xml, so issue registration fails.

**Comment by logpanic** [comment] 2015-10-20 16:26
Resolved article registration with PR #14

**Closed as completed by logpanic** 2015-10-20 16:26 UTC
